tri_platform_home:
    path:   /{page}
    defaults:
        _controller: TRIPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

tri_platform_view:
    path:   /advert/{id}
    defaults:
        _controller: TRIPlatformBundle:Advert:view
    requirements:
        id: \d+

tri_platform_add:
    path:   /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

tri_platform_edit:
    path:   /edit/{id}
    defaults:
        _controller: TRIPlatformBundle:Advert:edit
    requirements:
        id: \d+

tri_platform_delete:
    path:   /delete/{id}
    defaults:
        _controller: TRIPlatformBundle:Advert:delete
    requirements:
        id: \d+
